---
- hosts: all
  tasks:
   - name: download notepadd++
     win_get_url:
         url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.4.1/npp.8.4.1.Installer.x64.exe
         dest: C:\
   - name: install
     win_package:
         path: C:\npp.8.4.1.Installer.x64.exe
         productid: auto
         state: present
     register: output
   - debug: var=output 
